name: Build and release new version
run-name: Building (${{ github.event_name }} by ${{ github.actor }}) 
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  Create-Pyinstaller-Build:
    name: Create build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu, windows, macos]

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.4

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Create PyInstaller executable
        run: poetry run pyinstaller meow.spec

      - name: Upload build to storage
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: dist/*

  Create-Package-Build:
    name: Create universal package build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.4

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Create Package
        run: poetry build
      
      - name: Get package version
        id: version
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Rename package file
        run: mv dist/meow-${{ steps.version.outputs.VERSION }}-py3-none-any.whl dist/meow-universal-py3-none-any.whl

      - name: Upload build to storage
        uses: actions/upload-artifact@v3
        with:
          name: package-build
          path: |
            dist/*.whl

  Upload-Release:
    name: Upload release
    runs-on: ubuntu-latest
    needs: 
      - Create-Pyinstaller-Build
      - Create-Package-Build

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Download Windows build
        uses: actions/download-artifact@v3
        with:
          name: windows-build
          path: dist/

      - name: Download Linux build
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-build
          path: dist/
      
      - name: Download MacOS build
        uses: actions/download-artifact@v3
        with:
          name: macos-build
          path: dist/

      - name: Download Package build
        uses: actions/download-artifact@v3
        with:
          name: package-build
          path: dist/

      - name: Display all files
        run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          fail_on_unmatched_files: true
